apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 81
  selector:
    app: backend-deployment