apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 81
  selector:
    app: frontend-deployment